// AUTO-GENERATED by scripts/build_anim_registry.mjs — DO NOT EDIT.
// Discovered 3 animations by scanning src/animations/.
// Add/remove an animation by adding/removing its folder, then re-run the generator.
import type { AnimModule } from './_contract';
import document from './document';
import photo from './photo';
import section from './section';

const MODULES: AnimModule[] = [document, photo, section];
// lower priority is matched first (e.g. merge before stack); default 100.
export const ANIMATIONS: AnimModule[] = [...MODULES].sort((a, b) => (a.priority ?? 100) - (b.priority ?? 100));
