#!/usr/bin/env node
// build_anim_registry.mjs — DISCOVERY step of the animation plugin system.
// Scans src/animations/<kind>/index.tsx and writes src/animations/registry.generated.ts,
// the single list the renderer (AutoReel) reads. Adding an animation = drop a folder with an
// index.tsx that default-exports an AnimModule, then run this. Removing = delete the folder,
// run this. No central list to hand-edit. The render pipeline runs this before every render,
// so a buyer's "add the charts pack" just works: the folder appears, the scan finds it.
import { readdirSync, existsSync, writeFileSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const HERE = dirname(fileURLToPath(import.meta.url));
const ANIM_DIR = join(HERE, '..', 'src', 'animations');
const OUT = join(ANIM_DIR, 'registry.generated.ts');
const CATALOG = join(ANIM_DIR, 'catalog.generated.json');

// a valid animation folder: not starting with '_', has an index.tsx
const kinds = readdirSync(ANIM_DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory() && !d.name.startsWith('_'))
  .map((d) => d.name)
  .filter((name) => existsSync(join(ANIM_DIR, name, 'index.tsx')))
  .sort();  // alphabetical → deterministic file output; runtime sorts by priority

// Also emit a language-neutral CATALOG (kind + metadata) that the Python plan builder and
// classifier read to know which animations are INSTALLED — so the plan never emits (and the
// picker never offers) an animation whose folder isn't present. An empty animations dir =>
// empty catalog => a caption/host base with zero packs. Fields are parsed from index.tsx.
const field = (src, re) => { const m = src.match(re); return m ? m[1] : ''; };
const listField = (src, re) => {
  const raw = field(src, re);
  return raw ? raw.split(',').map((s) => s.trim().replace(/^['"]|['"]$/g, '')).filter(Boolean) : [];
};
const catalog = kinds.map((k) => {
  const src = readFileSync(join(ANIM_DIR, k, 'index.tsx'), 'utf8');
  return {
    kind: field(src, /kind:\s*'([^']+)'/) || k,
    description: field(src, /description:\s*'((?:[^'\\]|\\.)*)'/),
    category: field(src, /category:\s*'([^']+)'/),
    tags: listField(src, /tags:\s*\[([^\]]*)\]/),
    scenes: listField(src, /scenes:\s*\[([^\]]*)\]/),
  };
});
writeFileSync(CATALOG, JSON.stringify(catalog, null, 1) + '\n');

const imports = kinds.map((k) => `import ${k} from './${k}';`).join('\n');
const list = kinds.join(', ');
const body = `// AUTO-GENERATED by scripts/build_anim_registry.mjs — DO NOT EDIT.
// Discovered ${kinds.length} animation${kinds.length === 1 ? '' : 's'} by scanning src/animations/.
// Add/remove an animation by adding/removing its folder, then re-run the generator.
import type { AnimModule } from './_contract';
${imports}

const MODULES: AnimModule[] = [${list}];
// lower priority is matched first (e.g. merge before stack); default 100.
export const ANIMATIONS: AnimModule[] = [...MODULES].sort((a, b) => (a.priority ?? 100) - (b.priority ?? 100));
`;

writeFileSync(OUT, body);
console.log(`✓ registry: ${kinds.length} animation(s) [${list || 'none'}] -> ${OUT.replace(process.cwd() + '/', '')}`);
